#!/bin/bash

echo "🚀 Deploying Janus WebRTC Server to Render..."

echo "📋 Prerequisites:"
echo "1. Make sure you have a Render account"
echo "2. Connect your GitHub repository to Render"
echo "3. Ensure the janus-service directory is pushed to GitHub"

echo ""
echo "🔧 Deployment Steps:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' and select 'Web Service'"
echo "3. Connect your GitHub repository: https://github.com/Nbouchek/alcall"
echo "4. Configure the service:"
echo "   - Name: unifiedchat-janus-service"
echo "   - Root Directory: services/janus-service"
echo "   - Runtime: Docker"
echo "   - Build Command: docker build -t janus ."
echo "   - Start Command: docker run -p \$PORT:8088 janus"
echo "   - Plan: Starter"
echo ""
echo "5. Environment Variables:"
echo "   - PORT: 8088"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "⏳ Wait for deployment to complete (usually 5-10 minutes)"
echo ""
echo "🔍 After deployment:"
echo "1. Note the service URL (e.g., https://unifiedchat-janus-service.onrender.com)"
echo "2. Test the health endpoint: curl https://unifiedchat-janus-service.onrender.com/"
echo "3. Update frontend environment variables with the new Janus URL"
echo ""
echo "📝 Next steps after deployment:"
echo "1. Run: ./update_frontend_for_janus.sh <JANUS_URL>"
echo "2. Test audio calling with the new Janus service"
echo ""
echo "✅ Janus deployment instructions complete!"
