#!/bin/bash

echo "🛑 Stopping Old Audio Service on Render..."
echo ""
echo "📋 Instructions to stop the old audio service:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Find the service: 'unifiedchat-audio-service'"
echo "3. Click on the service to open its dashboard"
echo "4. Click the 'Suspend' button to stop the service"
echo "5. Confirm the suspension"
echo ""
echo "⚠️  Important:"
echo "- This will stop the old audio service from receiving requests"
echo "- The frontend will show 'Audio service unavailable' until Janus is deployed"
echo "- This is necessary to complete the migration to Janus"
echo ""
echo "🔍 Alternative: Delete the service entirely"
echo "1. In the service dashboard, click 'Settings'"
echo "2. Scroll down to 'Danger Zone'"
echo "3. Click 'Delete Service'"
echo "4. Confirm deletion"
echo ""
echo "✅ After stopping the old service, proceed with Janus deployment!"
