export default function handler(req, res) {
  res.status(200).json({
    NEXT_PUBLIC_AUTH_API_URL: process.env.NEXT_PUBLIC_AUTH_API_URL,
    NEXT_PUBLIC_MESSAGE_API_URL: process.env.NEXT_PUBLIC_MESSAGE_API_URL,
    NEXT_PUBLIC_REALTIME_API_URL: process.env.NEXT_PUBLIC_REALTIME_API_URL,
    NEXT_PUBLIC_JANUS_HTTP_URL: process.env.NEXT_PUBLIC_JANUS_HTTP_URL,
    NEXT_PUBLIC_JANUS_URL: process.env.NEXT_PUBLIC_JANUS_URL,
    NEXT_PUBLIC_REALTIME_HTTP_API_URL:
      process.env.NEXT_PUBLIC_REALTIME_HTTP_API_URL,
    NODE_ENV: process.env.NODE_ENV,
  });
}
