services:
  - type: web
    name: unifiedchat-janus-service
    runtime: docker
    region: oregon
    plan: starter
    buildCommand: docker build -t janus .
    startCommand: docker run -p $PORT:8088 -p 8089:8089 -p 8000:8000 janus
    envVars:
      - key: PORT
        value: 8088
      - key: JANUS_LOG_LEVEL
        value: "4"
      - key: JANUS_LOG_TIMESTAMPS
        value: "true"
    healthCheckPath: /janus/info
    autoDeploy: true
    numInstances: 1
