services:
  - type: web
    name: unifiedchat-janus-service
    runtime: docker
    region: oregon
    plan: starter
    envVars:
      - key: JANUS_LOG_LEVEL
        value: "4"
      - key: JANUS_LOG_TIMESTAMPS
        value: "true"
    healthCheckPath: /janus
    autoDeploy: true
    numInstances: 1
