services:
  - type: web
    name: unifiedchat-realtime-service
    runtime: docker
    region: oregon
    plan: starter
    buildCommand: docker build -t realtime-service .
    
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
