services:
  - type: web
    name: unifiedchat-user-service
    runtime: docker
    region: oregon
    plan: starter
    buildCommand: docker build -t user-service .
    envVars:
      - key: PORT
        value: 8081
      - key: DB_HOST
        value: "localhost"
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: "unifiedchat"
      - key: DB_USER
        value: "unifiedchat"
      - key: DB_PASSWORD
        value: "password123"
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
