services:
  - type: web
    name: unifiedchat-user-service
    runtime: docker
    region: oregon
    plan: starter
    buildCommand: docker build -t user-service .
    envVars:
      - key: PORT
        value: 8081
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
