services:
  - type: web
    name: unifiedchat-frontend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_AUTH_API_URL
        value: "https://unifiedchat-auth-service.onrender.com/api/v1"
      - key: NEXT_PUBLIC_MESSAGE_API_URL
        value: "https://unifiedchat-message-service.onrender.com"
      - key: NEXT_PUBLIC_REALTIME_API_URL
        value: "https://unifiedchat-realtime-service.onrender.com"
      - key: NEXT_PUBLIC_JANUS_URL
        value: "wss://unifiedchat-janus-service.onrender.com/janus"
      - key: NEXT_PUBLIC_JANUS_HTTP_URL
        value: "https://unifiedchat-janus-service.onrender.com"
      - key: NEXT_PUBLIC_FORCE_NORMAL_MODE
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1
