services:
  - type: web
    name: unifiedchat-frontend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_AUTH_API_URL
        value: "https://auth-service-6pcp.onrender.com"
      - key: NEXT_PUBLIC_MESSAGE_API_URL
        value: "https://message-service-j7kz.onrender.com"
      - key: NEXT_PUBLIC_REALTIME_API_URL
        value: "https://realtime-service-onfn.onrender.com"
      - key: NEXT_PUBLIC_JANUS_URL
        value: "wss://janus-service.onrender.com/janus"
      - key: NEXT_PUBLIC_JANUS_HTTP_URL
        value: "https://janus-service.onrender.com"
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1
