services:
  - type: web
    name: unifiedchat-auth-service
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .
    
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
