services:
  - type: web
    name: alcall-ai-service
    runtime: go
    region: frankfurt
    plan: starter # Or choose an appropriate plan
    buildCommand: go build -o main
    startCommand: ./main
    autoDeploy: true
    pullRequestPreviewsEnabled: true
