services:
  - type: web
    name: alcall-message-service
    runtime: docker
    region: frankfurt
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .

    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
